services:
  pia-tun:
    image: x0lie/pia-tun:latest
    container_name: pia-tun
    cap_add:
      - NET_ADMIN                                                             # Necessary
    cap_drop:
      - all                                                                   # Highly recommended
    environment:
      - TZ=America/New_York
      - PIA_LOCATION=ca_ontario,ca_ontario-so,ca_toronto,ca                   # Supports multiple options, chooses lowest latency
      - PS_CLIENT=qbittorrent
      - PROXY_ENABLED=true
      - LOCAL_NETWORKS=auto,192.168.1.0/24
    secrets:
      - pia_user
      - pia_pass
      - ps_user
      - ps_pass
    ports:
      - 8080:8080                                                             # qBittorrent port for web UI access
      - 9090:9090                                                             # Metrics
      - 1080:1080                                                             # SOCKS5
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/killswitch_up"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 3s

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads
    network_mode: "service:pia-tun"
    depends_on:
      pia-tun:
        condition: service_healthy                                            # condition: service_healthy + the killswitch_up healthcheck = gauranteed no startup leaks, but not really necessary

secrets:                                                                      # Supports pia_user, pia_pass, proxy_user, proxy_pass, ps_user, ps_pass
  pia_user:
    file: ./secrets/pia_user
  pia_pass:
    file: ./secrets/pia_pass
  ps_user:
    file: ./secrets/ps_user
  ps_pass:
    file: ./secrets/ps_pass