name: Readme Sync

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - '.github/workflows/readme.yml'
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: x0lie
  IMAGE_NAME: pia-tun

jobs:
  sync-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          readme-filepath: ./README.md
          enable-url-completion: true