name: Test

on:
  workflow_call:

env:
  DOCKERHUB_USERNAME: x0lie
  IMAGE_NAME: pia-tun

jobs:
  test:
    name: Run Test Suite (${{ matrix.config }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - config: minimal

          - config: full
            PIA_LOCATIONS: "ca_ontario, ca_ontario-so, ca_toronto"
            LOCAL_NETWORKS: "all"
            DNS: "tls://one.one.one.one, dns.quad9.net"
            PF_ENABLED: true
            PORT_FILE: "/port"
            PROXY_USER: "user"
            PROXY_PASS: "pass"
            SOCKS5_ENABLED: true
            SOCKS5_PORT: "1081"
            HTTP_PROXY_ENABLED: true
            HTTP_PROXY_PORT: "8889"
            METRICS_PORT: "9091"

          - config: legacy
            DNS: "system"
            PF_ENABLED: true
            SOCKS5_ENABLED: true
            HTTP_PROXY_ENABLED: true
            WG_BACKEND: "userspace"

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run integration tests
        env:
          PIA_USER: ${{ secrets.PIA_USER }}
          PIA_PASS: ${{ secrets.PIA_PASS }}
          PIA_LOCATIONS: ${{ matrix.PIA_LOCATIONS }}
          LOCAL_NETWORKS: ${{ matrix.LOCAL_NETWORKS }}
          DNS: ${{ matrix.DNS }}
          PF_ENABLED: ${{ matrix.PF_ENABLED }}
          PORT_FILE: ${{ matrix.PORT_FILE }}
          PROXY_USER: ${{ matrix.PROXY_USER }}
          PROXY_PASS: ${{ matrix.PROXY_PASS }}
          SOCKS5_ENABLED: ${{ matrix.SOCKS5_ENABLED }}
          SOCKS5_PORT: ${{ matrix.SOCKS5_PORT }}
          HTTP_PROXY_ENABLED: ${{ matrix.HTTP_PROXY_ENABLED }}
          HTTP_PROXY_PORT: ${{ matrix.HTTP_PROXY_PORT }}
          METRICS_PORT: ${{ matrix.METRICS_PORT }}
          WG_BACKEND: ${{ matrix.WG_BACKEND }}
        run: go test -v -tags integration -timeout 5m ./tests/integration/...

  result:
    name: Run Test Suite
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: |    
          [[ "${{ needs.test.result }}" == "success" ]] || exit 1
